### PR TITLE
Add anchor links for h3-6.

### PR DESCRIPTION
**Pull request by jgerigmeyer**

### CODE REVIEW

**Comment by jgerigmeyer** [comment]
[I want click-to-copy anchor links for headers.](https://trello.com/c/T0UW4E0y/46-i-want-click-to-copy-anchor-links-for-headers)

**Comment by jgerigmeyer** [comment]
@stacyk @sanajaved7 In today's mtg, Natalie pointed out that the existing site adds anchor links to all headers beyond `h1`, while we were only adding to `h2`. This addresses that.

**Review by sanajaved7 — APPROVED** [review]
Nice! I had a change to add anchor links to `h3` in the documentation story, so I can take that out after this is merged 🚀

**Comment by stacyk** [comment]
I don't think this is new to this PR, but was there discussion about how we should handle headings within a list? I don't think these specific headings should be list items, but there may be others.

implementation-heading-link
https://deploy-preview-43--sass-site-oddbird.netlify.app/implementation/

I see that some pages on their live site do not have all heading level anchor links: https://sass-lang.com/libsass 
This page is full of list item headings so maybe that is why they aren't linked?
PR for comparison: https://deploy-preview-43--sass-site-oddbird.netlify.app/libsass/

**Review by stacyk — APPROVED** [review]
Approving since the link icon over bullet isn't new and this code looks good. Maybe it is a non-issue what I captured in the previous comment?

**Comment by jgerigmeyer** [comment]
> I don't think this is new to this PR, but was there discussion about how we should handle headings within a list? I don't think these specific headings should be list items, but there may be others.

@stacyk Yeah, good questions. I noticed that too, and hoped no one else would. 😅 

I'm not 100% sure on the logic, but I think the old site is maybe only adding anchors in the blog section? I didn't see a good reason to try to limit that here (and I'm not 100% sure how), so I went for a more site-wide approach. But I agree the list headers with anchors don't look good, so I removed those in https://github.com/oddbird/sass-site/commit/0e386b66602bec3af8f18c836f2e5f0465dc8d60.

**Review by stacyk — APPROVED** [review]
Works for me with your latest update @jgerigmeyer  :)

**Pull request merged**
