### PR TITLE
Try out markdown-it-attrs

### PR DESCRIPTION
**Pull request by jgerigmeyer**
https://github.com/arve0/markdown-it-attrs

### CODE REVIEW

**Comment by jgerigmeyer** [comment]
This slightly backtracks on my [earlier comment](https://github.com/oddbird/sass-site/pull/19#discussion_r1117416920), now trying out [markdown-it-attrs](https://github.com/arve0/markdown-it-attrs) to use Markdown in places where we were only using markup because we needed to add classes/attrs.

@mirisuzanne @sanajaved7 Better or worse?

**Review by mirisuzanne — APPROVED** [review]
I think all those classes are a bit of a mess either way you do it, but I like this approach to it.

**Comment by sanajaved7** [comment]
Ok I'm not sure if I'm a fan 😅 I think it's because the syntax throws me off a bit - especially in the case of `## Contribute {#Contribute}` and the fact I'm so used to seeing the attributes in the traditional/other way. I was looking at the docs a bit more and I'm open to trying it out because it is certainly easier than switching the templates back to liquid for just attributes so that's a plus for sure.

**Comment by jgerigmeyer** [comment]
@sanajaved7 I completely agree! I'm not sure I like the new syntax (aside: would `## Contribute {id=Contribute}` be better?) but figure let's give it a shot and see if we get used to it.

**Pull request merged**
