### PR TITLE
Browser code editor debug

### PR DESCRIPTION
**Pull request by jamesnw**
## Description
Adds a console panel to playground. The most complicated portion is handling the polymorphic messages returned, with different formats for each of debug and error, and 2 formats for warn. The line number comes from the span, falling back to parsed from the stack trace, and  

Styling is not fully implemented. Future work includes clickable line numbers, and additional elements to draw attention to the errors.

## Steps to test/reproduce
_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._

This SCSS includes a variety of messages-

```
@mixin inset-divider-offset($offset, $padding) {
  $divider-offset: (2 * $padding) + $offset;
  @debug "divider offset: #{$divider-offset}";

  margin-left: $divider-offset;
  width: calc(100% - #{$divider-offset});
}
p{
  @include inset-divider-offset(1,2);
  @include inset-divider-offset(2,2);
}

@debug test;
@debug (12px/4px);
@warn user warn example;
@debug "<button onmouseover="alert('heck')">Test</button>";

@debug meta.modules('page-sizes')
```

## Show me
_Provide screenshots/animated gifs/videos if necessary._

### CODE REVIEW

**Comment by jamesnw** [comment]
https://trello.com/c/rtzzyuuy/15-surface-errors-warnings-to-interface

**Comment by jerivas** [comment]
@jamesnw I think we didn't show you this, but you can create a two-way link between Trello cards and PRs by using the little GitHub button on the sidebar of each card:

<p>image</p>

I also enabled [deploys previews](https://deploy-preview-62--sass-site-oddbird.netlify.app/playground/) for this branch on Netlify to ease the review process (by default only PRs based on `main` are previewed)

**Review by jerivas — COMMENTED** [review]
This is not about the code, but I wanted to share my ideas for the styling phase. I think we can take a few things from the browser console:

image

- Messages are clearly delimited by a border / separator
- Warnings and errors have distinct colors that make them pop
- Warnings and errors also have icons (debug could have an icon too)

And then maybe for a future phase if budget allows:

- Multiline messages are collapsed
- The line number is provided on the far right of each message. On click the user is taken to the line that produced the message

**Comment by jamesnw** [comment]
> This is not about the code, but I wanted to share my ideas for the styling phase. I think we can take a few things from the browser console:
> 
> image
> * Messages are clearly delimited by a border / separator
> * Warnings and errors have distinct colors that make them pop
> * Warnings and errors also have icons (debug could have an icon too)
> 
> And then maybe for a future phase if budget allows:
> 
> * Multiline messages are collapsed
> * The line number is provided on the far right of each message. On click the user is taken to the line that produced the message

I like the idea of using the dev tools console as the inspiration. The other possibility would be basing it off of a standard terminal, as that is the context in which users have seen these messages before, but I think the dev tools has a better UX.

**Comment by jamesnw** [comment]
I've merged this branch into #58 so we can review the playground as a whole.

**Pull request closed without merging**
